### ISSUE TITLE
Users seem to be getting themselves into a position where they see "StackLevel Too Deep" error

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co-curriculum/tic-tac-toe-rb#16]
This error become very hard to debug. I believe this happens because we stub `#gets` method to return a certain # of values. After these values are returned by gets, it returns nil (rather than error-ing out). It would be good to have raise a better error when users get into this situation

**Comment by abhishekpillai** [comment]
Example question here: https://learn.co/tracks/intro-to-ruby-web-development/ruby-basics/tic-tac-toe/tictactoe-rb?batch_id=286&question_uid=q-40d64952-603f-4763-bc77-852b5ccb8c2c&track_id=12307

**Comment by aturkewi** [comment]
Added note about this in the readme in PR #44
