### ISSUE TITLE
WIN_COMBO TEST

### ISSUE THREAD

**Issue by febbraiod** [learn-co-curriculum/tic-tac-toe-rb#20]
Hello,

All of the arrays tested for here are written in numerical order except one.  The vertical middle win should be 2,4,6 not 6,4,2.  I spoke with Kate and she confirmed.

./lib/tic_tac_toe.rb WIN_COMBINATIONS defines a constant WIN_COMBINATIONS with arrays for each win combination Failure/Error: expect(WIN_COMBINATIONS).to include([6,4,2]) expected [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]] to include [6, 4, 2]

**Comment by aviflombaum** [comment]
Fixed in a55bfa4 Thanks!
