### ISSUE TITLE
Position Inconsistantcy

### ISSUE THREAD

**Issue by febbraiod** [learn-co-curriculum/tic-tac-toe-rb#21]
It seems that as far as the spec files are concerned.  The #move method and the #position_taken method are using "position" in different ways.  #move is looking at it from the players perspective (1-9):

describe '#move' do
    it 'allows "X" player in the bottom right and "O" in the top left ' do
      board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
      move(board, 1, "O")
      move(board, 9, "X")

```
  expect(board).to eq(["O", " ", " ", " ", " ", " ", " ", " ", "X"])
end
```

  end

While the #position_taken wants to use (0-8):

describe '#position_taken?' do
    it 'returns true/false based on position in board' do
      board = ["X", " ", " ", " ", " ", " ", " ", " ", "O"]

```
  position = 0
  expect(position_taken?(board, position)).to be(true)

  position = 8
  expect(position_taken?(board, position)).to be(true)

  position = 1
  expect(position_taken?(board, position)).to be(false)

  position = 7
  expect(position_taken?(board, position)).to be(false)
end
```

  end

I know that I can still get my code to work anyway, but it seems a little confusing.

**Comment by aturkewi** [comment]
Fixed in PR #44 same as issue #35 

Thanks for raising this issue @febbraiod
