### ISSUE TITLE
open coverage/index.html

### ISSUE THREAD

**Issue by hebersandoval** [learn-co-curriculum/tic-tac-toe-rb#26]
Can not open the coverage/index.html
This is the error am getting:

➜  tic-tac-toe-rb-q-000 git:(master) ✗ open coverage/index.html
Couldn't get a file descriptor referring to the console

Thank you for your help.

Heber Sandoval

**Comment by AnnJohn** [comment]
Hi @hscoder has this issue been resolved for you? For all immediate questions, please use the Ask a Question tool in Learn and someone from our Learn Experts team will help you right away. Thanks!

**Comment by hebersandoval** [comment]
Ann,

I'll ask for help in the "ask a question" section. 

Thank you for your help.

Héber Sandoval 

-----Original Message-----
