### ISSUE TITLE
'gets' and 'chomp' can not be recognized by rake console

### ISSUE THREAD

**Issue by scottwansz** [learn-co-curriculum/tic-tac-toe-rb#32]
'gets' and 'chomp' can not be recognized by rake console:

[2] pry(main)> board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
=> [" ", " ", " ", " ", " ", " ", " ", " ", " "]
[3] pry(main)> play(board)
Please input 1-9:
Errno::ENOENT: No such file or directory @ rb_sysopen - console
from /home/nitrous/code/labs/tic-tac-toe-rb-002/lib/tic_tac_toe.rb:45:in `gets'

[5] pry(main)> turn(board)
Please input 1-9:
NoMethodError: undefined method `chomp' for nil:NilClass
from /home/nitrous/code/labs/tic-tac-toe-rb-002/lib/tic_tac_toe.rb:45:in`turn'

**Comment by AnnJohn** [comment]
Hi @scottwan there might be an issue with the code that you have, but we'll leave the issue open and look into it.

If you use the Ask a Question tool in Learn, someone from our support team will get back to you right away and help you out. Thanks!

**Comment by aturkewi** [comment]
@scottwan I'm not sure how you cam by this error. I'm going to close this PR for now, but if you'd like to get in touch with me to go over this, I'd be more than happy to better understand what was happening here. Feel free to re-open this issue if you'd like to do that and just @ mention me!
