### ISSUE TITLE
Use of "position" throughout tic-tac-toe

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/tic-tac-toe-rb#35]
I think it would be less confusing and better for beginners if use of the variable name "position" wasn't so ambiguous in the code/testing.

It's not a problem, just more of a suggestion: using the word "index" instead of "position". Using "position" interchangeably in the code/tests to mean position on the board, a string, and index into the array, a number is very confusing and frustrating.  I've seen tests use it both ways.  I'm not even the first person to think so (#21 ).

I'm willing to do the leg-work of making the pull request, but it's in several lessons and I want to get a 'green light'/'good idea' before I do it.

I would leave "position" as it is when it refers to the user's input, a string.
I would use "index" in code and tests to refer to: `index=position.to_i - 1`

What do you guys think?

**Comment by aturkewi** [comment]
Thanks @bhollan for the suggestion. I ended up going through all the TTT labs to straighten this out. Now position means 1-9 and index means 0-8. I also added a new method `#input_to_index` so that you only have to make the conversion once and we DRY up the code :)

Fixed in PR #44

**Comment by bhollan** [comment]
Awesome.  That's what I was trying to do with all the PRs in the TTT series.  Glad it got tackled!  Thanks!
