### ISSUE TITLE
01_tic_tac_toe_spec.rb error

### ISSUE THREAD

**Issue by ivanjankovic** [learn-co-curriculum/tic-tac-toe-rb#47]
describe '#valid_move?' do
    it 'returns true/false based on position' do
      board = [" ", " ", " ", " ", "X", " ", " ", " ", " "]

```
  position = 0
  expect(valid_move?(board, position)).to be_truthy

  position = 4
  expect(valid_move?(board, position)).to be_falsey

  position = -1
  expect(valid_move?(board, position)).to be_falsey
end
```

  end

board does not have a position 0 (zero), and position 5 is taken and not 4

**Comment by AnnJohn** [comment]
hi @ivanjanko apologies for the delay. we will need to make a bit more consistency with position and index numbers. in this case, position refers to index numbers. So, for example, you can see that index 0 is the first blank space there. Thanks
