### ISSUE TITLE
Error message when trying to submit a learn request

### ISSUE THREAD

**Issue by Zeitlin1** [learn-co-curriculum/tic-tac-toe-rb#50]
I'm getting this error message and I can't find the path to this.

// ♥ learn open tic-tac-toe-rb-ruby-intro-000  
Looking for lesson...  
Bundling...  
Opening lesson...  
Done.  
[22:35:15](master) tic-tac-toe-rb-ruby-intro-000  
// ♥ learn  
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method`this' for #<Gem::Specification
:0xc973cc learn-co-3.6.0> (NoMethodError)  
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'                           
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in`require'  
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-co-3.6.0/bin/learn:3:in `<top (required)>'                                                   
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn:23:in`load'  
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn:23:in `<main>'                                                                                
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`eval'  
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AnnJohn** [comment]
hi @Zeitlin1 this looks like a technical problem. Could you please use 'Ask a Question' and someone from our team will help you out. Thanks!
