### ISSUE TITLE
spec checking order

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/tic-tac-toe-rb#51]
It took me a long time to figure out !won(board) had to be called before full?(board) in the "draw?(board) function. Maybe I'm missing something, but I would think the spec should be able to allow for either "if !won?(board) && full?(board)" or "if full?(board) && !won?(board)"

**Comment by mdo5004** [comment]
Same issue.

The test 

#draw? calls won? and full? 

fails for the method

```
def draw?(board)
   full?(board) && !won?(board)
end
```

but passes for the method

```
def draw?(board)
   !won?(board) && full?(board)
end
```

**Comment by ghost** [comment]
Same issue.

**Comment by kwebster2** [comment]
@aturkewi 
This issue is still present. I had a student from the v-000 track with this issue.

**Comment by nikifi** [comment]
I came here to report this and see that its already here. Wasted so much time today trying to figure out why the test is not passing and it wasn't until I posted a question, and someone replied I thought of swapping them. Glad to see I am not crazy.

**Comment by aturkewi** [comment]
Tagging a couple of people in here to take a look at this :) @cjbrock @jmburges

**Comment by DakotaLMartinez** [comment]
Hey guys! 

Just had another student run into this issue today. [this PR](https://github.com/learn-co-curriculum/tic-tac-toe-rb/pull/56) fixes the issue.
