### ISSUE TITLE
Code Coverage section needs updated instructions for IDE

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/tic-tac-toe-rb#52]
The [code coverage section](https://github.com/learn-co-curriculum/tic-tac-toe-rb#code-coverage) needs to be updated w/ instructions for the IDE 🙂 

cc: @cjbrock @aturkewi

**Comment by aturkewi** [comment]
Added note on how to access code coverage from the Learn IDE. 
Thanks!
