### ISSUE TITLE
Help with Tic Tac Toe in Ruby -- almost done

### ISSUE THREAD

**Issue by achesky** [learn-co-curriculum/tic-tac-toe-rb#53]
I'm stuck on the 33rd failure -- Finished in 0.19731 seconds (files took 0.29317 seconds to load)                       
32 examples, 1 failure                    
Failed examples:                                                                 
rspec ./spec/02_play_spec.rb:36 # ./lib/tic_tac_toe.rb #play plays the first few turns 
of the game        

I have: 
def play(board)
  until over?(board) == true
    user_input = gets.strip
    turn(board)
  end
end

and it passes the 'plays the first turn of the game', but does not pass 'plays the first few turns of the game' -- not sure what's wrong and looking for help!

**Comment by scbly** [comment]
try while instead of until!

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
