### ISSUE TITLE
#won? returning nil if no winner causes the "checks if the game is won after every turn" test to fail

### ISSUE THREAD

**Issue by josh-stillman** [learn-co-curriculum/tic-tac-toe-rb#59]
I wrote my #won? method to return nil if there was no winner.  The lesson says that #won? should "return false/nil if there is no win combination present in the board."  Everything worked fine in the CLI with a nil return value, but nil was causing the error below.  When I changed #win? to return false if no win, instead of nil, all the tests passed.  I'd suggest someone take a look and verify whether the lesson should be edited to required #won? to return false if no winner.  If nil won't work, I'd suggested editing the sentence in the lesson to say that #won? should ""return **false** if there is no win combination present in the board."  Thanks!

Here's the test that was failing with a nil return value from #won? if no win was present.

1) ./lib/tic_tac_toe.rb #play checks if the game is won after every turn
     Failure/Error: expect(self).to receive(:won?).at_least(:twice).and_return(false, false, true)
       (#<RSpec::ExampleGroups::LibTicTacToeRb_2::Play:0x0000000197d910>).won?(*(any args))
           expected: at least 3 times with any arguments
           received: 2 times with any arguments
     # ./spec/02_play_spec.rb:58:in `block (3 levels) in <top (required)>'
Finished in 0.04753 seconds (files took 0.36594 seconds to load)
44 examples, 1 failure

**Comment by justinddaniel** [comment]
A similar problem occurs when the tests for play look for the draw? method to be called

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
