### ISSUE TITLE
Tedious to rewrite and/or find all my methods

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/tic-tac-toe-rb#6]
I didn't want to have to re-write all of the methods I previously wrote, but I'd forgotten which labs were associated with which lessons. It was tedious to click back through several lessons / units to find all of the methods I needed (and I knew worked). Once I had them all, it was fun to assemble the play method but I feel like we could/should do more for the user so that this lab is about "putting the pieces together" rather than "finding all of the pieces you previously worked on AND THEN putting them together". Particularly since learn doesn't make it particularly easy to search/find past lessons, had to a lot of hunt & peck work to find, combined with finding the right folders on my computer.

**Comment by aviflombaum** [comment]
addressed in 49d057d
