### ISSUE TITLE
"Cats Game!" vs "Cat's Game!"

### ISSUE THREAD

**Issue by josh-stillman** [learn-co-curriculum/tic-tac-toe-rb#60]
The tests for procedural TTT requires "**Cats** Game!" for a draw, while the tests for object-oriented TTT require "Cat's Game" for a draw.  I suggest changing the test for the procedural TTT to require "Cat's Game!" on a draw as well.

**Comment by gj** [comment]
Updated; thanks @Josh-Stillman !
