### ISSUE TITLE
There seems to be a name collision when testing #move with "rake console".

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/tic-tac-toe-rb#64]
Hello! When I tested my methods using "rake console", most of them worked, except for #move. I need to preface this by saying that my #move method passed the rspec tests.

When I was using "rake console", I created the variable board = [" ", " ", " ", " ", " ", " ", " ", " ", " "] then called #move with
move(board, 2, "X")
I then received this error: 
ArgumentError: wrong number of arguments (given 4, expected 2..3)
from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:513:in `mv'

I tried other calls to #move by sending it other indexes and replacing "X" with "O", but I got the same result. I also received the same error after explicitly defining the #move method within "rake console" itself.

From what I heard from one of the TC's, it may be a name collision. If that's the case, I think "rake console" may need to be reprogrammed to look for #move and other methods inside of lib/tic_tac_toe.rb first, before looking elsewhere. I can't say for sure, though, as I am not familiar with how "rake console" works. 

Thank you for looking into this!

Regards,
Sdcrouse

**Comment by cdhenry** [comment]
I worked on this issue with Sdcrouse, and can confirm that it seems to be a naming collision while inside rake console.  When we changed the name of the method to something other than 'move' it worked just fine; however the tests for this lab call for the method to be named 'move'.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
