### ISSUE TITLE
Consider making the play tests less opinionated

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/tic-tac-toe-rb#66]
let's say a student's code is as follows:

def over?(board)
   won?(board) || full?(board)
end

def play(board)
    until over?
        turn(board)
    end
end

The way the test is written, this will result in an infinite loop:

    it 'checks if the game is draw after every turn' do
      board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
      allow($stdout).to receive(:puts)
      allow(self).to receive(:gets).and_return("1", "2", "3")

      expect(self).to receive(:draw?).at_least(:twice).and_return(false, false, true)

      play(board)
    end

So it will keep calling play(board), fail to see the draw? method called, call play(board) again, and so on. 
Granted checking for draw is a bit more accurate than checking for full, but this is incredibly hard for a student to debug! The infinite loop is very hard to understand!

**Comment by cjbrock** [comment]
Hi @justinddaniel! As a developer, I can tell you that I've run up against infinite loops more times than I can count. It's a real world situation that happens much more often than we'd really like. Part of our job at Flatiron School is to prepare you for the outside world, and that means putting you in situations where infinite loops happen. I'm glad you ended up figuring it out in the end.

// <3 Corinna
