### ISSUE TITLE
Move method needs to flip/flop between X & O

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/tic-tac-toe-rb#7]
I may have missed this, but I figured it out from a failing test, but it turns out that the move method I previously wrote (which was hard coded to move "X") actually needs to flip flop between moving X and O on subsequent turns. This should have been obvious, I suppose, but I think we might want to call that out in the description of this lab?

**Comment by aviflombaum** [comment]
Ya, it's suppose to use a default argument. WIll check.

**Comment by matbalez-zz** [comment]
the move method uses a default but you need to invoke with with current_player. when i solved this, i don't think i realized that at the time

**Comment by aturkewi** [comment]
Changed tests and updated the readme here to _remove_ the default argument from the `#move` method for this lab as there is no use for it here and can cause more confusion than anything else.
