### ISSUE TITLE
some strange html rendering

### ISSUE THREAD

**Issue by mdanapalmer** [learn-co-curriculum/tic-tac-toe-rb#70]
just as a heads up it looks like some html may be rendering improperly here:
https://screencast.com/t/BCbozWD4JA

https://learn.co/tracks/full-stack-web-development-v6/intro-to-ruby-development/ruby-tic-tac-toe/tic-tac-toe-in-ruby?batch_id=306&question_id=149969&track_id=43149#fullscreen

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @mdanapalmer.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
