### ISSUE TITLE
02_play_spec.rb Tic Tac Toe error

### ISSUE THREAD

**Issue by dno1995** [learn-co-curriculum/tic-tac-toe-rb#72]
It seems to me that everything is working on my tic-tac-toe-rb but because of how I chose to write my #over? method I am still getting an error, but my #over? method works exactly how it is supposed to.
Here is a screenshot of the method and error.
![image](https://user-images.githubusercontent.com/40639830/48280005-4d31dd00-e420-11e8-99bd-45e37235aa32.png)
If you can't read the image here is what it says:
def over?(board)
  !won?(board).nil? || draw?(board) == true
end
Failures:
  1) ./lib/tic_tac_toe.rb #play checks if the game is won after every turn
     Failure/Error: expect(self).to receive(:won?).at_least(:twice).and_return(false, false, true)
       (#<RSpec::ExampleGroups::LibTicTacToeRb_2::Play "checks if the game is won after every turn" (./spec/02_play_spec.rb:52)>).won?(*(any args
))
           expected: at least 3 times with any arguments
           received: 1 time with any arguments
      ./spec/02_play_spec.rb:58:in `block (3 levels) in <top (required)>'

But if I replace the method above with this one:

def over?(board)
  if won?(board) || draw?(board)
    return true
  else
    return false
  end
end

Everything works just fine. Does my first method have an issue or do the tests just not really allow me to use that method?

**Comment by cjbrock** [comment]
Hey @dno1995!

It looks like you don't have an error with the curriculum, but an error with the way that your code is being written. That's totally ok! If you check in with one of our Technical Coaches at Ask A Question, they should be able to explain to you why the code that you've pasted in above isn't quite the solution that you're looking for. 

Thanks!
Corinna

**Comment by dno1995** [comment]
Hi @cjbrock 

I am sorry if I was not clear in my post above. 

The code above works perfectly, the current tests for the lab don't mark it as passing even though my code works perfectly, so I thought it might mean that the test needs to be rewritten to allow for my working solution. 

I would love to suggest how the test should be modified, but I am not sure what the changes should be.
