### ISSUE TITLE
IDE is not showing files

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/tic-tac-toe-rb#73]
The console says the following:
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 26\"": unknown
learn open tic-tac-toe-rb-v-000

**Comment by drakeltheryuujin** [comment]
Hi @guerilla17,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

I'm sorry, and good luck! 💙
