### ISSUE TITLE
"Sorry, something went wrong. Please try again" error 

### ISSUE THREAD

**Issue by dana0522** [learn-co-curriculum/tic-tac-toe-rb#77]
Hi, I've been getting the same error message whenever I open IDE. I cannot access my previously written codes or the tool itself because of this. I can see all of the lesson materials, but for some reason, IDE is not working. Can I get someone to resolve this ASAP??

**Comment by maxwellbenton** [comment]
Hi @dana0522,

Sorry to hear you were having difficulty with this lab. Unfortunately, I was unable to recreate this issue, but can confirm that this lesson is currently forking and working as intended. If you are still working on any Learn lessons and experiencing this issue, please reach out to support@learn.co for further assistance.

Thank you!
