### ISSUE TITLE
lib file suddenly disappear

### ISSUE THREAD

**Issue by engahmed10** [learn-co-curriculum/tic-tac-toe-rb#79]
I have problem to open In TicTacToe.rb lab , when i open lab ,lib file suddenly disappear, and give error below : 
// ♥ learn Looking for lesson... Opening lesson... Bundling... [!] There was an error parsing Gemfile: unexpected fraction part after numeric literal - gem install bundler -v 1.17.3# A sample Gemfile ^~~~ /home/lite-system-7983/tic-tac-toe-rb-bootcamp-prep-000/Gemfile:1: syntax error, unexpected tFLOAT, expecting do or '{' or '(' gem install bundler -v 1.17.3# A sample Gemfile ^~~~~~~. Bundler cannot continue. # from /home/lite-system-7983/tic-tac-toe-rb-bootcamp-prep-000/Gemfile:1 # ------------------------------------------- > gem install bundler -v 1.17.3# A sample Gemfile # source

**Comment by lizbur10** [comment]
Hello! I'm so sorry you ran into this problem - hopefully you were able to get it resolved. 

For future reference, the best place to get assistance with this type of issue is [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
