### ISSUE TITLE
Tests want elements in winning arrays to be in a particular order.

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/tic-tac-toe-rb#9]
This issue was avoided in the Game Status lab, because of a custom matcher created in spec_helper.rb.

When checking WIN_COMBINATIONS the game_status_spec.rb used include_array() as follows:

describe 'WIN_COMBINATIONS' do
    it 'defines a constant WIN_COMBINATIONS with arrays for each win combination' do
      expect(WIN_COMBINATIONS.size).to eq(8)

```
  expect(WIN_COMBINATIONS).to include_array([0,1,2])
  expect(WIN_COMBINATIONS).to include_array([3,4,5])
  expect(WIN_COMBINATIONS).to include_array([6,7,8])
  expect(WIN_COMBINATIONS).to include_array([0,3,6])
  expect(WIN_COMBINATIONS).to include_array([1,4,7])
  expect(WIN_COMBINATIONS).to include_array([2,5,8])
  expect(WIN_COMBINATIONS).to include_array([0,4,8])
  expect(WIN_COMBINATIONS).to include_array([6,4,2])
end
```

  end

that method was defined in spec_helper as follows:

RSpec::Matchers.define :include_array do |expected|
  match do |actual|
    actual.any?{|array| match_array(expected).matches?(array)}
  end
end

In this lab, it doesn't have that in the spec_helper, so it doesn't use include_array(). instead, it uses include(), which cares about the order of elements.

I changed my 01_tic_tac_toe_spec.rb and the spec_helper for it, so that I could pass the tests irrespective of order, and submitted a pull request, but I wasn't sure if that was sufficient, or if I should raise the issue here.

**Comment by aviflombaum** [comment]
Fixed in a55bfa4
